### PR TITLE
Require result of verify functions to be used

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Will switch to just `Result<(), VerifyError>` in v0.11

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
ACK

**Review by zoedberg — CHANGES_REQUESTED** [review]
Build fails with:
```
error[E0063]: missing field `static_entropy` in initializer of `MultiSource`
   --> /home/zoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rgb-wallet-0.10.9/src/psbt/dbc.rs:119:22
    |
119 |         let source = mpc::MultiSource {
    |                      ^^^^^^^^^^^^^^^^ missing `static_entropy`
```

**Comment by dr-orlovsky** [comment]
@zoedberg you posted this to a wrong PR

But that PR is targeted for v0.11 so of course it won't compile with 0.10 stack

**Comment by zoedberg** [comment]
@dr-orlovsky Sorry, I haven't noticed that! Are you planning to apply this fix also to the 0.10 version?

**Comment by dr-orlovsky** [comment]
Which fix? From this PR or from the static entropy?

**Comment by zoedberg** [comment]
I'm confused. I was talking about this PR. I've patched commit_verify in rgb-lib like this:

`commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "fix/verify_not_used" }` 

and received the build error I posted here

**Comment by dr-orlovsky** [comment]
@zoedberg All right, I see. My bad. So I did start `master` for `0.11` - and did this PR on top of that changes coming from the PRs which were targeting v0.11 and were already merged into the master.

Thus, this PR must be against `v0.10` branch and not master. Will fix that.

**Comment by dr-orlovsky** [comment]
@zoedberg done. Should work now.

**Comment by dr-orlovsky** [comment]
Anyway, my tests shows that all these changes are void, since rust enforces `must_use` only on the top-level type (which is result) and not onto boolean. If the boolean is unused, there still no compiler warning...

**Review by zoedberg — APPROVED** [review]
It builds and all our tests pass, thus ACK
